server:
  port: 8083
spring:
  application:
    name: Eureka-service
swagger2:
  enable: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/